### ISSUE TITLE
ಠ_ಠ

### ISSUE THREAD

**Issue by DrKat123** [Jonathan50/this-is-epic-os#1]
Rly
It's just Windows 10, edited in GIMP

**Comment by Jonathan50** [comment]
![](http://i.cubeupload.com/MBI4uC.png) lol


No, it's not Windows 10 edited in GIMP, it's made from Scratch in GIMP except for the Firefox on Win10 screenshot from Wikipedia.

**Comment by DrKat123** [comment]
ಠ_ಠ
I hate yiu

**Comment by Jonathan50** [comment]
Since you don't seem to have anything constructive to say, I'm closing...

**Comment by DrKat123** [comment]
That's good
